package plugins

// All returns a pre-populated list of plugins written for renum's code generator.
var All = []Constructor{
	NewCamelCasePlugin,
	NewCodesPlugin,
	NewCommandCasePlugin,
	NewConstPlugin,
	NewDefinitionPlugin,
	NewDescriptionsPlugin,
	NewErrorsPlugin,
	NewFlagsPlugin,
	NewHeaderPlugin,
	NewHTTPCodesPlugin,
	NewJSONPlugin,
	NewKindsPlugin,
	NewMessagesPlugin,
	NewNamesPlugin,
	NewOSExitCodesPlugin,
	NewPackageInfoPlugin,
	NewParsePlugin,
	NewPascalCasePlugin,
	NewPathsPlugin,
	NewScreamingCasePlugin,
	NewSnakeCasePlugin,
	NewSourcesPlugin,
	NewSQLPlugin,
	NewStringerPlugin,
	NewTextPlugin,
	NewTyperPlugin,
	NewValuesPlugin,
	NewYAMLPlugin,
	NewYARPCCodesPlugin,
}
