package config

// Serializers holds information about which serializers should be generated by the renum generator.
type Serializers struct {
	Text   bool `json:"text,omitempty" mapstructure:"text,omitempty" yaml:"text,omitempty" toml:"text,omitempty"`
	JSON   bool `json:"json,omitempty" mapstructure:"json,omitempty" yaml:"json,omitempty" toml:"json,omitempty"`
	YAML   bool `json:"yaml,omitempty" mapstructure:"yaml,omitempty" yaml:"yaml,omitempty" toml:"yaml,omitempty"`
	CSV    bool `json:"csv,omitempty" mapstructure:"csv,omitempty" yaml:"csv,omitempty" toml:"csv,omitempty"`
	SQL    bool `json:"sql,omitempty" mapstructure:"sql,omitempty" yaml:"sql,omitempty" toml:"sql,omitempty"`
	Gob    bool `json:"gob,omitempty" mapstructure:"gob,omitempty" yaml:"gob,omitempty" toml:"gob,omitempty"`
	Binary bool `json:"binary,omitempty" mapstructure:"binary,omitempty" yaml:"binary,omitempty" toml:"binary,omitempty"`
	Flags  bool `json:"flags,omitempty" mapstructure:"flags,omitempty" yaml:"flags,omitempty" toml:"flags,omitempty"`
}
